# Generated by Django 4.2.1 on 2023-05-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cabinet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="date_birthday",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
