# Generated by Django 4.2.1 on 2023-05-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cabinet", "0002_alter_userprofile_date_birthday"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="discord",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telegram",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
